version: '3.9'

services:
    database:
        container_name: kola-postgres
        image: postgres:15.2
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: 'exit 0'
    migration:
        container_name: kola-migrations
        image: liquibase/liquibase:4.21.0
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - ./src/database/migrations:/liquibase/changelog
        command:
            'update --username=${DB_USERNAME} --password=${DB_PASSWORD} --url=${DB_MIGRATION_URL} --liquibase-schema-name=public
            --changelogFile="./master.json"'
