import { orm } from '../../shared/orm'

export const makes = [
    {
        'models': [
            '500',
            'Grande Punto',
        ],
        'name': 'Abrath',
    },
    {
        'models': [
            'MDX',
        ],
        'name': 'Acura',
    },
    {
        'models': [
            'U5',
        ],
        'name': 'Airways',
    },
    {
        'models': [
            '145',
            '146',
            '147',
            '155',
            '156',
            '156 SW',
            '159',
            '159 SW',
            '164',
            '166',
            '33',
            '33 SW',
            '75',
            '90',
            'Alfasud',
            'Alfetta',
            'Brera',
            'Cross Wagon',
            'Giulia',
            'Giulietta',
            'GT',
            'GTV',
            'MiTo',
            'RZ/SZ',
            'Spider',
            'Sprint',
            'Stelvio',
            'Tonale',
        ],
        'name': 'Alpha Romeo',
    },
    {
        'models': [
            '10',
            '244',
        ],
        'name': 'Aro',
    },
    {
        'models': [
            'DB',
            'DB7',
            'DB9',
            'DBS',
            'DBX',
            'Lagonda',
            'V8',
            'Vanquish',
            'Vantage',
            'Virage',
            'Volante',
        ],
        'name': 'Aston Martin',
    },
    {
        'models': [
            '100',
            '100 Avant',
            '200',
            '50',
            '60',
            '80',
            '80 Avant',
            '90',
            'A1',
            'A2',
            'A3',
            'A3 Cabrio',
            'A3 Coupe',
            'A4',
            'A4 Allroad',
            'A4 Avant',
            'A4 Cabrio',
            'A5 Cabrio',
            'A5 Coupe',
            'A5 Sportback',
            'A6',
            'A6 Allroad',
            'A6 Avant',
            'A7',
            'A8',
            'e-tron',
            'Q2',
            'Q3',
            'Q4 e-tron',
            'Q5',
            'Q7',
            'Q8',
            'R8',
            'RS2',
            'RS3',
            'RS4',
            'RS5',
            'RS6',
            'RS7',
            'S1',
            'S2',
            'S3',
            'S4',
            'S4 Avant',
            'S5',
            'S6',
            'S6 Avant',
            'S8',
            'TT',
            'V8',
        ],
        'name': 'Audi',
    },
    {
        'models': [
            'Arnage',
            'Azure',
            'Bentayga',
            'Brooklands',
            'Continental',
            'Continental GT',
            'Continental GT Speed',
            'Eight',
            'Flying Spur',
            'Mulsanne',
            'S1',
            'T1',
            'Turbo R',
        ],
        'name': 'Bently',
    },
    {
        'models': [
            '1802',
            '2002',
            'i3',
            'i4',
            'i7',
            'i8',
            'iX',
            'iX1',
            'iX3',
            'M2',
            'M3',
            'M3 Cabriolet',
            'M4',
            'M5',
            'M5 Touring',
            'M6',
            'serija 1',
            'serija 2',
            'serija 2 Active Tourer',
            'serija 2 Gran Coupe',
            'serija 2 Gran Tourer',
            'serija 3',
            'serija 3 Cabriolet',
            'serija 3 Compact',
            'serija 3 Coupe',
            'serija 3 Gran Turismo',
            'serija 3 Touring',
            'serija 4 Cabriolet',
            'serija 4 Coupe',
            'serija 4 Gran Coupe',
            'serija 5',
            'serija 5 Gran Turismo',
            'serija 5 Touring',
            'serija 6',
            'serija 6 Gran Coupe',
            'serija 7',
            'serija 8',
            'X1',
            'X2',
            'X3',
            'X4',
            'X5',
            'X6',
            'X7',
            'Z1',
            'Z3',
            'Z4',
            'Z8',
        ],
        'name': 'BMW',
    },
    {
        'models': [
            'Chiron',
            'Veyron',
        ],
        'name': 'Bugatti',
    },
    {
        'models': [
            'Allante',
            'Coupe de Ville',
            'CTS',
            'Eldorado',
            'Escalade',
            'Fleetwood',
            'Seville',
            'SRX',
            'STS',
            'XLR',
        ],
        'name': 'Cadillac',
    },
    {
        'models': [
            'Avalanche',
            'Aveo',
            'Beretta',
            'Blazer',
            'Camaro',
            'Captiva',
            'Cavalier',
            'Corvette',
            'Cruze',
            'Epica',
            'Equinox',
            'Evanda',
            'HHR',
            'Kalos',
            'Lacetti',
            'Lumina',
            'Malibu',
            'Matiz',
            'Nubira',
            'Orlando',
            'Silverado',
            'Spark',
            'Suburban',
            'Tacuma',
            'Tahoe',
            'TrailBlazer',
            'Trans Sport',
            'Trax',
            'Volt',
        ],
        'name': 'Chevrolet',
    },
    {
        'models': [
            '300C',
            '300M',
            'Crossfire',
            'Daytona',
            'ES',
            'Grand Voyager',
            'LeBaron',
            'Neon',
            'New Yorker',
            'Pacifica',
            'PT Cruiser',
            'Saratoga',
            'Sebring',
            'Stratus',
            'Viper',
            'Vision',
            'Voyager',
        ],
        'name': 'Chrysler',
    },
    {
        'models': [
            '2CV',
            'AX',
            'Berlingo',
            'BX',
            'BX Break',
            'C-Crosser',
            'C-Elysee',
            'C-Zero',
            'C1',
            'C15',
            'C2',
            'C25',
            'C3',
            'C3 Aircross',
            'C3 Picasso',
            'C3 Pluriel',
            'C35',
            'C4',
            'C4 Aircross',
            'C4 Cactus',
            'C4 Grand Picasso',
            'C4 Picasso',
            'C5',
            'C5 Aircross',
            'C5 Break',
            'C5 X',
            'C6',
            'C8',
            'CX',
            'DS',
            'DS3',
            'DS4',
            'DS5',
            'Evasion',
            'GS',
            'Jumper',
            'Jumpy',
            'Nemo',
            'Saxo',
            'SM',
            'Spacetourer',
            'Visa',
            'Xantia',
            'Xantia Break',
            'XM',
            'XM Break',
            'Xsara',
            'Xsara Break',
            'Xsara Coupe',
            'Xsara Picasso',
            'ZX',
            'ZX Break',
        ],
        'name': 'Citroen',
    },
    {
        'models': [
            'Ateca',
            'Born',
            'Formentor',
            'Leon',
        ],
        'name': 'Cupra',
    },
    {
        'models': [
            'Dokker',
            'Duster',
            'Jogger',
            'Lodgy',
            'Logan',
            'Sandero',
            'Solenza',
            'Spring',
            'Supernova',
        ],
        'name': 'Dacia',
    },
    {
        'models': [
            'Chairman',
            'Espero',
            'Evanda',
            'Kalos',
            'Korando',
            'Lacetti',
            'Lanos',
            'Leganza',
            'Matiz',
            'Musso',
            'Nexia',
            'Nubira',
            'Racer',
            'Tacuma',
            'Tico',
        ],
        'name': 'Daewoo',
    },
    {
        'models': [
            'Applause',
            'Charade',
            'Charade Compact',
            'Copen',
            'Cuore',
            'Feroza',
            'Freeclimber',
            'Gran Move',
            'Hijet',
            'Materia',
            'Move',
            'Rocky',
            'Sirion',
            'Terios',
            'Trevis',
            'YRV',
        ],
        'name': 'Daihatsu',
    },
    {
        'models': [
            'Seres 3',
            'Seres 5',
        ],
        'name': 'DFSK',
    },
    {
        'models': [
            'Avenger',
            'Caliber',
            'Challenger',
            'Charger',
            'Durango',
            'Grand Caravan',
            'Journey',
            'Magnum',
            'Nitro',
            'RAM',
            'Stealth',
            'Viper',
        ],
        'name': 'Dodge',
    },
    {
        'models': [
            'Mini Bus K07',
            'Mini Bus V07',
            'Mini Truck K01',
            'Mini Truck K02',
            'Mini Van K05',
        ],
        'name': 'Dongfeng',
    },
    {
        'models': [
            'DS3',
            'DS3 Crossback',
            'DS4',
            'DS4 Crossback',
            'DS5',
            'DS7',
            'DS7 Crossback',
            'DS9',
        ],
        'name': 'DS Automobiles',
    },
    {
        'models': [
            'Nevo',
        ],
        'name': 'Electra',
    },
    {
        'models': [
            '296',
            '308',
            '328',
            '348',
            '355',
            '360',
            '430',
            '456',
            '458',
            '488',
            '512',
            '550',
            '575',
            '599',
            '612',
            '812 Superfast',
            'California',
            'Dino',
            'Enzo',
            'F40',
            'F50',
            'F8 Tributo',
            'Mondial',
            'Portofino',
            'Roma',
            'Testarossa',
        ],
        'name': 'Ferrari',
    },
    {
        'models': [
            '124',
            '125',
            '126',
            '127',
            '130',
            '131',
            '132',
            '500',
            '500L',
            '500X',
            'Albea',
            'Autobianchi',
            'Barchetta',
            'Brava',
            'Bravo',
            'Cinquecento',
            'Coupe',
            'Croma',
            'Doblo',
            'Ducato',
            'Fiorino',
            'Freemont',
            'Fullback',
            'Grande Punto',
            'Idea',
            'Linea',
            'Marea',
            'Marea Weekend',
            'Multipla',
            'Palio',
            'Palio Weekend',
            'Panda',
            'Punto',
            'Punto Cabrio',
            'Punto Evo',
            'Qubo',
            'Regata',
            'Ritmo',
            'Scudo',
            'Sedici',
            'Seicento',
            'Spider',
            'Stilo',
            'Stilo SW',
            'Strada',
            'Talento',
            'Tempra',
            'Tempra SW',
            'Tipo',
            'Ulysse',
            'Uno',
            'X 1/9',
        ],
        'name': 'Fiat',
    },
    {
        'models': [
            'Karma',
        ],
        'name': 'Fisker',
    },
    {
        'models': [
            'Aerostar',
            'B-Max',
            'Bronco',
            'C-Max',
            'Capri',
            'Contour',
            'Cougar',
            'Ecosport',
            'Edge',
            'Escape',
            'Escort',
            'Escort Cabriolet',
            'Escort Karavan',
            'Escort Van',
            'Excursion',
            'Expedition',
            'Explorer',
            'F',
            'Fiesta',
            'Fiesta Courier',
            'Focus',
            'Focus C-Max',
            'Focus Coupe Cabriolet',
            'Focus Karavan',
            'Freestyle',
            'Fusion',
            'Galaxy',
            'Ghia',
            'Granada',
            'Grand C-Max',
            'GT',
            'Ka',
            'Kuga',
            'Maverick',
            'Mondeo',
            'Mondeo Karavan',
            'Mustang',
            'Orion',
            'Probe',
            'Puma',
            'Ranger',
            'S-Max',
            'Scorpio',
            'Sierra',
            'Sierra Karavan',
            'StreetKa',
            'Taunus',
            'Taurus',
            'Tourneo Connect',
            'Tourneo Courier',
            'Transit',
            'Transit Custom',
            'Windstar',
        ],
        'name': 'Ford',
    },
    {
        'models': [
            'Envoy',
            'Sierra 1500',
        ],
        'name': 'GMC',
    },
    {
        'models': [
            'Coolbear',
            'Cowry',
            'Florid',
            'Hover',
            'Hover H5',
            'i7',
            'Peri',
            'Wingle',
        ],
        'name': 'Great Wall Motor',
    },
    {
        'models': [
            'Accord',
            'Accord Aerodeck',
            'Accord Coupe',
            'Civic',
            'Civic Aerodeck',
            'Civic Coupe',
            'Civic HB',
            'Civic Sedan',
            'Concerto',
            'CR-V',
            'CR-Z',
            'CRX',
            'e',
            'FR-V',
            'HR-V',
            'Insight',
            'Integra',
            'Jazz',
            'Legend',
            'Logo',
            'NSX',
            'Odyssey',
            'Prelude',
            'Ridgeline',
            'S2000',
            'Shuttle',
            'Stream',
        ],
        'name': 'Honda',
    },
    {
        'models': [
            'H1',
            'H2',
            'H3',
        ],
        'name': 'Hummer',
    },
    {
        'models': [
            'Accent',
            'Atos',
            'Bayon',
            'Coupe',
            'Elantra',
            'Equus',
            'Excel',
            'Galloper',
            'Getz',
            'Grandeur',
            'H-1',
            'H-100',
            'i10',
            'i20',
            'i30',
            'i30 Fastback',
            'i40',
            'Ioniq',
            'Ioniq 5',
            'ix20',
            'ix35',
            'ix55',
            'Kona',
            'Lantra',
            'Lantra Wagon',
            'Matrix',
            'Pony',
            'S Coupe',
            'Santa Fe',
            'Santamo',
            'Sonata',
            'Terracan',
            'Tiburon',
            'Trajet',
            'Tucson',
            'Veloster',
            'XG',
        ],
        'name': 'Hyundai',
    },
    {
        'models': [
            'EX25',
            'EX30',
            'EX35',
            'EX37',
            'FX',
            'FX30',
            'FX50',
            'FX60',
            'G25',
            'G35',
            'G37',
            'I35',
            'JX35',
            'M30',
            'M35h',
            'M37',
            'M45',
            'Q30',
            'Q45',
            'Q50',
            'Q60',
            'Q70',
            'QX30',
            'QX50',
            'QX56',
            'QX70',
        ],
        'name': 'Infiniti',
    },
    {
        'models': [
            'Amigo',
            'Campo',
            'D-MAX',
            'Gemini',
            'Impulse',
            'Midi',
            'Mu',
            'Trooper',
        ],
        'name': 'Isuzu',
    },
    {
        'models': [
            'Massif',
        ],
        'name': 'Iveco',
    },
    {
        'models': [
            'ES2',
            'ES4',
        ],
        'name': 'Jac',
    },
    {
        'models': [
            'Daimler',
            'E-Pace',
            'E-Type',
            'F-Pace',
            'F-Type',
            'I-Pace',
            'Mk2',
            'S-Type',
            'Sovereign',
            'X-Type',
            'XE',
            'XF',
            'XJ',
            'XK',
            'XKR',
        ],
        'name': 'Jaguar',
    },
    {
        'models': [
            'Cherokee',
            'CJ',
            'Commander',
            'Compass',
            'Grand Cherokee',
            'Patriot',
            'Renegade',
            'Wagoneer',
            'Willys',
            'Wrangler',
        ],
        'name': 'Jeep',
    },
    {
        'models': [
            'Besta',
            'Carens',
            'Carnival',
            'Ceed (cee\'d)',
            'Ceed (cee\'d) Sportswagon',
            'Cerato',
            'Clarus',
            'Clarus Wagon',
            'Elan',
            'EV6',
            'Joice',
            'K-2700',
            'Magentis',
            'Niro',
            'Opirus',
            'Optima',
            'Optima Sportswagon',
            'Picanto',
            'Pregio',
            'Pride',
            'Pride Wagon',
            'Pro ceed',
            'Retona',
            'Rio',
            'Rocsta',
            'Sephia',
            'Shuma',
            'Sorento',
            'Soul',
            'Spectra',
            'Sportage',
            'Stinger',
            'Stonic',
            'Venga',
            'XCeed',
        ],
        'name': 'KIA',
    },
    {
        'models': [
            '110',
            '111',
            '112',
            '1300',
            'Aleko',
            'Desetka',
            'Kalina',
            'Karavan',
            'Niva',
            'Nova',
            'Samara',
        ],
        'name': 'Lada',
    },
    {
        'models': [
            'Aventador',
            'Countach',
            'Diablo',
            'Gallardo',
            'Huracan',
            'Miura',
            'Murcielago',
            'Reventon',
            'Urus',
        ],
        'name': 'Lamborghini',
    },
    {
        'models': [
            'Beta',
            'Dedra',
            'Dedra SW',
            'Delta',
            'Fulvia',
            'Kappa',
            'Kappa SW',
            'Lybra',
            'Lybra SW',
            'Musa',
            'Phedra',
            'Prisma',
            'Stratos',
            'Thema',
            'Thema SW',
            'Thesis',
            'Voyager',
            'Y',
            'Zeta',
        ],
        'name': 'Lancia',
    },
    {
        'models': [
            '90',
            'Defender',
            'Discovery',
            'Discovery Sport',
            'Freelander',
            'Range Rover',
            'Range Rover Evoque',
            'Range Rover Sport',
            'Range Rover Velar',
        ],
        'name': 'Land Rover',
    },
    {
        'models': [
            'CT',
            'ES',
            'GS',
            'GX',
            'IS',
            'LC',
            'LS',
            'LX',
            'NX',
            'RC',
            'RX',
            'SC',
            'UX',
        ],
        'name': 'Lexus',
    },
    {
        'models': [
            'Towncar',
        ],
        'name': 'Lincon',
    },
    {
        'models': [
            'Elan',
            'Elise',
            'Esprit',
            'Exige',
            'Super Seven',
        ],
        'name': 'Lotus',
    },
    {
        'models': [
            'Fairway FX4',
        ],
        'name': 'LTI',
    },
    {
        'models': [
            'Bolero',
            'Goa',
            'Thar',
        ],
        'name': 'Mahindra',
    },
    {
        'models': [
            '222',
            '224',
            '228',
            '3200',
            '418',
            '420',
            '422',
            '424',
            '430',
            'Biturbo',
            'Coupe',
            'Ghibli',
            'GranSport',
            'GranTurismo',
            'Grecale',
            'Levante',
            'MC20',
            'Quattroporte',
            'Shamal',
            'Spyder',
        ],
        'name': 'Maserati',
    },
    {
        'models': [
            '57',
            '62',
        ],
        'name': 'Maybach',
    },
    {
        'models': [
            '121',
            '1500',
            '2',
            '3',
            '323',
            '323 C',
            '323 F',
            '323 HB',
            '323 Karavan',
            '323 P',
            '323 Sedan',
            '5',
            '6',
            '6 Sport Combi',
            '626',
            '626 Wagon',
            '929',
            'B-2200',
            'B-2500',
            'BT-50',
            'CX-3',
            'CX-30',
            'CX-5',
            'CX-60',
            'CX-7',
            'CX-9',
            'Demio',
            'E-2200',
            'MPV',
            'MX-3',
            'MX-30',
            'MX-5',
            'MX-6',
            'Premacy',
            'RX-7',
            'RX-8',
            'Tribute',
            'Xedos 6',
            'Xedos 9',
        ],
        'name': 'Mazda',
    },
    {
        'models': [
            '116',
            '123',
            '124',
            '126 coupe',
            '180',
            '190',
            'A-klasa',
            'AMG GT',
            'B-klasa',
            'C klasa-SportCoupe',
            'C-klasa',
            'C-klasa Coupe',
            'C-klasa T-model',
            'Citan',
            'CL',
            'CLA klasa',
            'CLC',
            'CLK cabrio',
            'CLK coupe',
            'CLS klasa',
            'E-klasa',
            'E-klasa Cabrio',
            'E-klasa Coupe',
            'E-klasa T-model',
            'EQA',
            'EQB',
            'EQC',
            'EQE',
            'EQS',
            'EQV',
            'G',
            'GD 300',
            'GL',
            'GLA',
            'GLB',
            'GLC',
            'GLC Coupe',
            'GLE',
            'GLE Coupe',
            'GLK',
            'GLS',
            'M-klasa',
            'MB-100',
            'ML',
            'R klasa',
            'S klasa',
            'serija 100',
            'serija 200',
            'serija 500',
            'SL roadster ',
            'SLK roadster',
            'SLR Mclaren',
            'Sprinter',
            'V-klasa',
            'Van',
            'Vaneo',
            'Viano',
            'Vito',
            'X-klasa',
        ],
        'name': 'Mercedes-Benz',
    },
    {
        'models': [
            '5',
            'EHS',
            'F',
            'HS',
            'Marvel R',
            'SV',
            'TF',
            'ZR',
            'ZS',
            'ZS EV',
            'ZT 190',
            'ZTT',
        ],
        'name': 'MG',
    },
    {
        'models': [
            'Cabrio',
            'Clubman',
            'Cooper',
            'Countryman',
            'One',
        ],
        'name': 'Mini',
    },
    {
        'models': [
            '3000 GT',
            'ASX',
            'Attrage',
            'Carisma',
            'Colt',
            'Diamante',
            'Eclipse',
            'Eclipse Cross',
            'Galant',
            'Grandis',
            'i-MiEV',
            'L200',
            'L300',
            'L400',
            'Lancer',
            'Outlander',
            'Pajero',
            'Sigma',
            'Space Gear',
            'Space Runner',
            'Space Star',
            'Space Wagon',
            'Starion',
        ],
        'name': 'Mitsubishi',
    },
    {
        'models': [
            '100NX',
            '200SX',
            '280ZX',
            '300ZX',
            '350Z',
            '370Z',
            'Almera',
            'Almera Tino',
            'Altima',
            'Ariya',
            'Bluebird',
            'Cherry',
            'GT-R',
            'Juke',
            'Juke Nismo',
            'King Cab',
            'Leaf',
            'Maxima',
            'Micra',
            'Murano',
            'Navara',
            'Note',
            'NV200',
            'NV300',
            'Pathfinder',
            'Patrol',
            'Pick Up',
            'Pixo',
            'Prairie',
            'Primastar',
            'Primera',
            'Primera Karavan',
            'Pulsar',
            'Qashqai',
            'Qashqai+2',
            'Quest',
            'Serena',
            'Silvia',
            'Skyline',
            'Sunny',
            'Sunny Karavan',
            'Terrano',
            'Tiida',
            'Titan',
            'Trade',
            'Vanette',
            'X-Trail',
            'Xterra',
        ],
        'name': 'Nissan',
    },
    {
        'models': [
            'Ro 80',
        ],
        'name': 'NSU',
    },
    {
        'models': [
            'Adam',
            'Agila',
            'Ampera',
            'Antara',
            'Ascona',
            'Astra',
            'Astra Cabrio',
            'Astra Classic',
            'Astra Coupe',
            'Astra Karavan',
            'Astra Van',
            'Calibra',
            'Campo',
            'Cascada',
            'Combo',
            'Commodore',
            'Corsa',
            'Corsa Combo',
            'Crossland',
            'Diplomat',
            'Frontera',
            'Grandland',
            'GT',
            'Insignia',
            'Insignia Karavan',
            'Kadett',
            'Kadett Cabrio',
            'Kadett Combo',
            'Kadett Karavan',
            'Karl',
            'Manta',
            'Meriva',
            'Mokka',
            'Monterey',
            'Monza',
            'Movano',
            'Olympia',
            'Omega',
            'Omega Karavan',
            'Rekord',
            'Senator',
            'Signum',
            'Sintra',
            'Speedster',
            'Tigra',
            'Vectra',
            'Vectra Karavan',
            'Vivaro',
            'Zafira',
        ],
        'name': 'Opel',
    },
    {
        'models': [
            'Polestar 1',
            'Polestar 2',
        ],
        'name': 'Polestar',
    },
    {
        'models': [
            'Aztek',
            'Bonneville',
            'Fiero',
            'Firebird',
            'Grand Am',
            'Grand Prix',
            'Trans Am',
            'Trans Sport',
        ],
        'name': 'Pontiac',
    },
    {
        'models': [
            '356',
            '911',
            '912',
            '914',
            '924',
            '928',
            '944',
            '959',
            '968',
            '996',
            'Boxster',
            'Carrera GT',
            'Cayenne',
            'Cayman',
            'Macan',
            'Panamera',
            'Taycan',
        ],
        'name': 'Porsche',
    },
    {
        'models': [
            '313',
            '315',
            '318',
            '415',
            '418',
            'serija 300',
            'serija 400',
        ],
        'name': 'Proton',
    },
    {
        'models': [
            'G',
            'Haflinger',
            'Pinzgauer',
        ],
        'name': 'Puch',
    },
    {
        'models': [
            '1007',
            '104',
            '106',
            '107',
            '108',
            '2008',
            '204',
            '205',
            '205 Cabrio',
            '206',
            '206 Break',
            '206 CC',
            '207',
            '207 CC',
            '207 SW',
            '208',
            '3008',
            '301',
            '304',
            '305',
            '306',
            '306 Break',
            '306 Cabrio',
            '306 Sedan',
            '307',
            '307 Break',
            '307 CC',
            '307 SW',
            '308',
            '308 CC',
            '308 SW',
            '309',
            '4007',
            '4008',
            '404',
            '405',
            '405 Break',
            '406',
            '406 Break',
            '406 Coupe',
            '407',
            '407 Coupe',
            '407 SW',
            '408',
            '5008',
            '504',
            '508',
            '508 SW',
            '604',
            '605',
            '607',
            '806',
            '807',
            'Bipper',
            'Boxer',
            'Expert',
            'iOn',
            'J5',
            'Partner',
            'RCZ',
            'Rifter',
            'Traveller',
        ],
        'name': 'Pugeot',
    },
    {
        'models': [
            '11',
            '14',
            '18',
            '19',
            '19 Cabrio',
            '19 Chamade',
            '20',
            '21',
            '21 Nevada',
            '25',
            '30',
            '4',
            '5',
            '5 Express',
            '9',
            'Alpine',
            'Austral',
            'Avantime',
            'Captur',
            'Clio',
            'Espace',
            'Express',
            'Fluence',
            'Fuego',
            'Grand Espace',
            'Grand Modus',
            'Grand Scenic',
            'Kadjar',
            'Kangoo',
            'Kangoo Express',
            'Koleos',
            'Laguna',
            'Laguna Break',
            'Laguna Coupe',
            'Laguna Grandtour',
            'Latitude',
            'Master',
            'Megane',
            'Megane Break',
            'Megane Cabriolet',
            'Megane Classic',
            'Megane Conquest',
            'Megane Coupe',
            'Megane Grandcoupe',
            'Megane Grandtour',
            'Megane Scenic',
            'Megane Sedan',
            'Modus',
            'Safrane',
            'Scenic',
            'Sport Spider',
            'Talisman',
            'Thalia',
            'Trafic',
            'Twingo',
            'Vel Satis',
            'WIND',
            'ZOE',
        ],
        'name': 'Renault',
    },
    {
        'models': [
            'Corniche',
            'Flying Spur',
            'Ghost',
            'Park Ward',
            'Phantom',
            'Silver Cloud',
            'Silver Dawn',
            'Silver Seraph',
            'Silver Shadow',
            'Silver Spirit',
            'Silver Spur',
            'Wraith',
        ],
        'name': 'Rolls-Royce',
    },
    {
        'models': [
            '100',
            '111',
            '114',
            '116',
            '200',
            '214',
            '216',
            '218',
            '220',
            '25',
            '400',
            '414',
            '416',
            '418',
            '420',
            '45',
            '600',
            '618',
            '620',
            '625',
            '75',
            '800',
            '820',
            '825',
            '827',
            'City Rover',
            'Metro',
            'MGF',
            'Montego',
            'Streetwise',
        ],
        'name': 'Rover',
    },
    {
        'models': [
            '9.0',
            '9.3',
            '9.5',
            '9.7',
            '90',
            '900',
            '9000',
            '96',
            '99',
        ],
        'name': 'Saab',
    },
    {
        'models': [
            '300',
            '350',
        ],
        'name': 'Santana',
    },
    {
        'models': [
            'Alhambra',
            'Altea',
            'Arona',
            'Arosa',
            'Ateca',
            'Cordoba',
            'Cordoba Vario',
            'Exeo',
            'Ibiza',
            'Inca',
            'Leon',
            'Malaga',
            'Marbella',
            'Mii',
            'Tarraco',
            'Terra',
            'Toledo',
        ],
        'name': 'Seat',
    },
    {
        'models': [
            '105',
            '120',
            '130',
            '135',
            'Citigo',
            'Enyaq iV',
            'Fabia',
            'Fabia Combi',
            'Fabia Sedan',
            'Favorit',
            'Favorit Pick Up',
            'Felicia',
            'Felicia Combi',
            'Felicia Pick Up',
            'Forman',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Octavia',
            'Octavia Combi',
            'Pick Up',
            'Rapid',
            'Roomster',
            'Scala',
            'Superb',
            'Superb Combi',
            'Yeti',
        ],
        'name': 'Škoda',
    },
    {
        'models': [
            'crossblade',
            'EQ fortwo',
            'forfour',
            'fortwo cabrio',
            'fortwo coupe',
            'roadster',
        ],
        'name': 'Smart',
    },
    {
        'models': [
            'Actyon',
            'Korando',
            'Kyron',
            'Musso',
            'Rexton',
            'Rodius',
            'Tivoli',
        ],
        'name': 'SsangYong',
    },
    {
        'models': [
            '700 SDX',
            'B9 Tribeca',
            'Baja',
            'BRZ',
            'Forester',
            'Impreza',
            'Impreza Compact',
            'Impreza Sedan',
            'Justy',
            'Legacy',
            'Legacy Wagon',
            'Leone',
            'Leone Wagon',
            'Levorg',
            'Libero',
            'Outback',
            'SVX',
            'Trezia',
            'Tribeca',
            'Vivio',
            'XT',
            'XV',
        ],
        'name': 'Subaru',
    },
    {
        'models': [
            'Across',
            'Alto',
            'Baleno',
            'Baleno HB',
            'Baleno sedan',
            'Baleno Wagon',
            'Capuccino',
            'Carry Van',
            'Celerio',
            'Grand Vitara',
            'Ignis',
            'Jimny',
            'Kizashi',
            'Liana',
            'Maruti',
            'Samurai',
            'Splash',
            'Swace',
            'Swift',
            'Swift Cabrio',
            'Swift HB',
            'Swift Sedan',
            'SX4',
            'SX4 S-Cross',
            'Verona',
            'Vitara',
            'Wagon R+',
            'X-90',
            'XL7',
        ],
        'name': 'Suzuki',
    },
    {
        'models': [
            'Indica',
            'Indigo',
            'Xenon',
        ],
        'name': 'Tata',
    },
    {
        'models': [
            'Model 3',
            'Model S',
            'Model X',
            'Model Y',
            'Roadster',
        ],
        'name': 'Tesla',
    },
    {
        'models': [
            '4Runner',
            'Auris',
            'Auris karavan',
            'Avensis',
            'Avensis Verso',
            'Avensis Wagon',
            'Aygo',
            'bZ4X',
            'C-HR',
            'Camry',
            'Carina',
            'Carina Wagon',
            'Celica',
            'Corolla',
            'Corolla HB',
            'Corolla Sedan',
            'Corolla Verso',
            'Corolla Wagon',
            'GT86',
            'Hiace',
            'Highlander',
            'Hilux',
            'iQ',
            'Land Cruiser',
            'Lexus',
            'MR2',
            'Paseo',
            'Picnic',
            'Previa',
            'Prius',
            'Proace Verso',
            'RAV4',
            'Sienna',
            'Starlet',
            'Supra',
            'Tercel',
            'Urban Cruiser',
            'Verso',
            'Verso-S',
            'Yaris',
            'Yaris Cross',
            'Yaris Verso',
        ],
        'name': 'Toyota',
    },
    {
        'models': [
            '601',
            'Cabrio',
        ],
        'name': 'Trabant',
    },
    {
        'models': [
            '469',
        ],
        'name': 'UAZ',
    },
    {
        'models': [
            '240',
            '340',
            '360',
            '440',
            '460',
            '480',
            '740',
            '760',
            '780',
            '850',
            '850 Karavan',
            '940',
            '940 Karavan',
            '960',
            '960 Karavan',
            'C30',
            'C40',
            'C70',
            'S40',
            'S60',
            'S60 Cross Country',
            'S70',
            'S80',
            'S90',
            'V40',
            'V40 Cross Country',
            'V50',
            'V60',
            'V60 Cross Country',
            'V70',
            'V90',
            'V90 Cross Country',
            'XC40',
            'XC60',
            'XC70',
            'XC90',
        ],
        'name': 'Volvo',
    },
    {
        'models': [
            'Amarok',
            'Arteon',
            'Beetle',
            'Bora',
            'Bora Variant',
            'Buggy',
            'Caddy',
            'Caravelle',
            'Corrado',
            'Crafter',
            'CrossGolf',
            'Derby',
            'Eos',
            'Fox',
            'Golf 1',
            'Golf 2',
            'Golf 3',
            'Golf 3 Variant',
            'Golf 4',
            'Golf 4 Variant',
            'Golf 5',
            'Golf 5 Variant',
            'Golf 6',
            'Golf 6 Variant',
            'Golf 7',
            'Golf 7 Variant',
            'Golf 8',
            'Golf Cabrio',
            'Golf Plus',
            'Golf Sportsvan',
            'Hro',
            'ID.3',
            'ID.4',
            'ID.5',
            'Jetta',
            'LT-35',
            'Lupo',
            'Multivan',
            'Passat',
            'Passat CC',
            'Passat Variant',
            'Phaeton',
            'Polo',
            'Polo Classic',
            'Polo Variant',
            'R32',
            'Santana',
            'Scirocco',
            'Sharan',
            'T-Cross',
            'T-Roc',
            'Taigo',
            'Taro',
            'Tiguan',
            'Tiguan Allspace',
            'Touareg',
            'Touran',
            'Transporter',
            'Up!',
            'Vento',
        ],
        'name': 'Volkswagen',
    },
    {
        'models': [
            '1.o',
            '311',
            '353',
        ],
        'name': 'Wartburg',
    },
    {
        'models': [
            'Kitty',
            'Yoyo',
        ],
        'name': 'XEV',
    },
    {
        'models': [
            '45',
            '55',
            '60',
            '65',
            'Florida',
            'Poly',
            'Skala',
            'Tempo',
        ],
        'name': 'Yugo',
    },
    {
        'models': [
            '10',
            '101',
            '128',
            '750',
            '850',
            'Poly',
            'Tempo',
            'Yugo',
        ],
        'name': 'Zastava',
    },
    {
        'models': [
            'D2',
            'D2 Sport',
        ],
        'name': 'Zhidou',
    },
]

export const createMakes = makes.map((make) => {
    return orm.make.create({
        data: {
            models: {
                createMany: {
                    data: make.models.map((model) => {
                        return {
                            name: model,
                            updatedAt: new Date(),
                        }
                    }),
                },
            },
            name: make.name,
            updatedAt: new Date(),
        },
    })
})

export const makeSeed = [
    ...createMakes,
]
